In [ ]:
#assignment 2:data wrangling and exploratory analysis
## dataset:palmer archipelago penguine data
**source:**kaggle-palmer archipelago(antarctica)penguine data
**Dataset URL:** https://www.kaggle.com/datasets/parulpandey/palmer-archipelago-antarctica-penguin-data

**License:** CC0: Public Domain

**Why I chose this dataset:** I chose the Palmer Penguins dataset because it is beginner-friendly and contains both numerical
and categorical data. It also contains missing values, making it suitable for 
practicing data cleaning, feature engineering, NumPy computations, and exploratory data analysis.

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
# Load the dataset
df = pd.read_csv("data/raw/penguins_size.csv")

# Display the first 5 rows
df.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [18]:
#dataset shape
print("dataset shape:")
print(df.shape)

#colimn names
print("\ncolumn names:")
print(df.columns.tolist())

#data types
print("\nData types:")
print(df.dtypes)

#null value per column
print("\nNull counts per column:")
print(df.isnull().sum())

#unique value per column
print("\nunique-value counts per column:")
print(df.nunique())

dataset shape:
(344, 7)

column names:
['species', 'island', 'culmen_length_mm', 'culmen_depth_mm', 'flipper_length_mm', 'body_mass_g', 'sex']

Data types:
species                  str
island                   str
culmen_length_mm     float64
culmen_depth_mm      float64
flipper_length_mm    float64
body_mass_g          float64
sex                      str
dtype: object

Null counts per column:
species               0
island                0
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

unique-value counts per column:
species                3
island                 3
culmen_length_mm     164
culmen_depth_mm       80
flipper_length_mm     55
body_mass_g           94
sex                    3
dtype: int64

In [20]:
#check for duplicate rows
print("number of duplicate rows:",df.duplicated().sum())

number of duplicate rows: 0

In [33]:
#clean the missing values
#create a copy of orignl dataset for cleaning

clean_df=df.copy()

#fill missing numeric value with the median

numeric_columns=[
    "culmen_length_mm",
    "culmen_depth_mm",
    "flipper_length_mm",
    "body_mass_g"
]

for column in numeric_columns:
    clean_df[column] = clean_df[column].fillna(clean_df[column].median())

 #fill missing values in the sex column with the most commmon value
clean_df["sex"] = clean_df["sex"].fillna(clean_df["sex"].mode()[0])

#no duplicate rows were found,so no rows were removed
print("duplicate rows:",clean_df.duplicated().sum())
      
 #check missing values after cleaning

print("\nmissing values after cleaning:")
print(clean_df.isnull().sum())

#check data types
print("\ndata types after cleaning:")
print(clean_df.dtypes)

duplicate rows: 0

missing values after cleaning:
species              0
island               0
culmen_length_mm     0
culmen_depth_mm      0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

data types after cleaning:
species                  str
island                   str
culmen_length_mm     float64
culmen_depth_mm      float64
flipper_length_mm    float64
body_mass_g          float64
sex                      str
dtype: object

In [36]:
#priny the shape before the groupby/merge transform
print("shape before transformm:",clean_df.shape)

#calculate aerage body mass and flipper length for each species
species_stats = clean_df.groupby("species").agg(averag_body_mass=("body_mass_g","mean"),
average_flipper_length=("flipper_length_mm","mean")).reset_index()

#dispay the grouped staistic
print("\nspecies statistics:")
print(species_stats)

#merge the species statistics back into the main dataframe
clean_df = clean_df.merge(species_stats, on="species",how="left")

#print the shape after transform
print("\nshape after transform:",clean_df.shape)

#dispay the first 5 rows
clean_df.head()

shape before transformm: (344, 7)

species statistics:
     species  averag_body_mass  average_flipper_length
0     Adelie       3702.960526              190.000000
1  Chinstrap       3733.088235              195.823529
2     Gentoo       5067.741935              217.024194

shape after transform: (344, 9)

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex,averag_body_mass,average_flipper_length
0,Adelie,Torgersen,39.10,18.7,181.0,3750.0,MALE,3702.960526,190.0
1,Adelie,Torgersen,39.50,17.4,186.0,3800.0,FEMALE,3702.960526,190.0
2,Adelie,Torgersen,40.30,18.0,195.0,3250.0,FEMALE,3702.960526,190.0
3,Adelie,Torgersen,44.45,17.3,197.0,4050.0,MALE,3702.960526,190.0
4,Adelie,Torgersen,36.70,19.3,193.0,3450.0,FEMALE,3702.960526,190.0

In [39]:
#print shape before the pivot transform
print("shape of cleaned dataframe before pivot:",clean_df.shape)

#create a pivot table showing average body mass by species and sex
body_mass_pivot = clean_df.pivot_table(
    values="body_mass_g",
    index="species",
    columns="sex",
    aggfunc="mean"
)
print("\naverage body mass by species and sex:")
print(body_mass_pivot)

#print the shape of the pivot table
print("\nshape of pivot table:",body_mass_pivot.shape)

shape of cleaned dataframe before pivot: (344, 9)

average body mass by species and sex:
sex             .       FEMALE         MALE
species
Adelie        NaN  3368.835616  4011.708861
Chinstrap     NaN  3527.205882  3938.970588
Gentoo     4875.0  4679.741379  5416.923077

shape of pivot table: (3, 3)